/* Duel d'Helvara : textes anglais des cartes et des lieux.
   n = nom, fx = effet. Un nom absent garde le nom français (noms propres). */
window.HELVARA_EN = {
  fac: { helvara:"Helvara", primordial:"Primordial", desir:"Desire", jugement:"Judgement" },
  rar: { D:"Starter", C:"Common", R:"Rare", E:"Epic", L:"Legendary", U:"Ultra-Legendary", T:"Token" },
  cards: {
    passante:{n:"Ouchy Passer-by", fx:""},
    coursier:{n:"Flon Courier", fx:"On Reveal: draw 1 card."},
    ishara:{fx:"Ongoing: your other cards here have +1."},
    felix:{fx:"On Reveal: your next card costs 1 less."},
    veilleur:{n:"Underground Watchman", fx:""},
    remi:{fx:"On Reveal: +2 for each card destroyed or discarded since the start of the game."},
    celeste:{fx:"On Reveal: if you are not winning here when she arrives (not counting Céleste), +3."},
    vasseur:{fx:"On Reveal: +4 Power in two turns."},
    costumes:{n:"The Suits", fx:"Ongoing: +4 if the Agent of Thoth is in play."},
    colosse:{n:"Colossus of Lake Geneva", fx:""},
    doyenne:{n:"The Elder", fx:"Ongoing: your other Helvara cards have +1, in every location."},
    esquille:{n:"The Splinter", fx:"On Reveal: destroy the weakest enemy card here."},
    araignee:{n:"Crystal Spider", fx:"On Reveal: weaken every enemy card here by 1."},
    troll:{n:"The Troll", fx:"On Reveal: destroy your other weakest card here."},
    vritra:{fx:"On Reveal: no one can play here anymore."},
    yarden:{fx:"On Reveal: +4 if you have cards in all 3 locations (cards played this turn count)."},
    nyx:{fx:"On Reveal: destroy the strongest enemy card here. Nothing protects it."},
    apsu:{fx:"On Reveal: enemy cards here lose their effects. +6 if Yarden Weiss is on your side."},
    kitsune:{fx:"On Reveal: leave a 2-Power Illusion in another location."},
    uzume:{fx:"Enemy effects can neither target nor destroy her, except those where « nothing protects it »."},
    freyr:{fx:"On Reveal: +1 energy next turn. Ongoing: +2 if Freya is here."},
    maeve:{fx:"On Reveal: if you are winning here, +3."},
    izzy:{fx:"On Reveal: takes the Power of the strongest enemy card here, if it is higher (6 at most)."},
    devote:{n:"Devotee of Xochiquetzal", fx:""},
    hathor:{fx:"Ongoing: −1 to enemy cards here."},
    ishtar:{fx:"Ongoing: at the end of turns 1 to 5, −1 to the strongest enemy card here."},
    anat:{fx:"On Reveal: destroy your other weakest card here and gain its Power."},
    bastet:{fx:"On Reveal: +2 to your other cards here."},
    freya:{fx:"Ongoing: +4 if Freyr is here."},
    artemis:{n:"Artemis", fx:"On Reveal: −2 to the weakest enemy card here. +2 if Izzy is on your side."},
    eos:{n:"Eos", fx:"On Reveal: draw 1 card, 2 if Persephone is on your side."},
    morrigan:{fx:"Ongoing: you win ties here."},
    thot:{n:"Agent of Thoth", fx:"On Reveal: −2 to the strongest enemy card here."},
    persephone:{n:"Persephone", fx:"On Reveal: this location's effect stops."},
    skadi:{fx:"On Reveal: −3 to a random enemy card in another location."},
    eir:{fx:"Ongoing: your cards here can be neither destroyed nor weakened."},
    ixchel:{fx:"On Reveal: −3 to the strongest enemy card, in any location."},
    inanna:{fx:"On Reveal: every card here returns to its base Power, on both sides."},
    oya:{fx:"On Reveal: turn the strongest enemy card here into a 1-Power card with no effect."},
    sekhmet:{fx:"On Reveal: destroy every other card here with 2 Power or less, on both sides."},
    jordan:{n:"Jordan, the Creator", fx:"Can't be weakened. On Reveal: add Yarden Weiss to your hand from your deck."},
    jordan_n:{n:"Jordan, the Narrator", fx:"On Reveal: add to your hand, from your deck, a card that can form a Fusion with Jordan."},
    lilith:{fx:"On Reveal: the strongest enemy card here (6 or less) switches to your side. If your side is full, it is destroyed."},
    psyche:{n:"Psyche", fx:"Ongoing: your cards here can't go below 1. On Reveal: +2 to your weakest card here."},
    tlazol:{fx:"On Reveal: your weakened cards here return to their base Power. +2 for each."},
    eris:{n:"Eris", fx:"On Reveal: move the strongest enemy card here to another location."},
    idunn:{fx:"Ongoing: at the end of turns 1 to 5, +1 to your weakest card here."},
    durga:{fx:"On Reveal: destroy the strongest enemy card here if it has 7 or more. Otherwise, +3."},
    amaterasu:{fx:"Ongoing: your cards can't be weakened, in all 3 locations."},
    hecate:{n:"Hecate", fx:"On Reveal: draw 2 cards."},
    selene:{n:"Selene", fx:"Ongoing: +3 from turn 5, when the moon rises."},
    ereshkigal:{fx:"On Reveal: destroy every enemy card here with 3 Power or less. Nothing protects them."},
    pele:{fx:"On Reveal: the lava deals −2 to every other card here, on both sides."},
    ares:{n:"Ares", fx:"On Reveal: −1 to each enemy card here, and +1 for each."},
    nergal:{fx:"On Reveal: −1 to every enemy card, in all 3 locations. Ongoing: +3 while Ereshkigal is on your side."},
    rusalka:{fx:"On Reveal: destroy the weakest enemy card here if it has 2 or less."},
    mere:{n:"The Mother of Ash", fx:"On Reveal: leave a 2-Power Ashling in each of your other locations."},
    nuee:{n:"The Swarm of Mirrors", fx:"On Reveal: copy the Power of your strongest card here."},
    charognard:{n:"The M2 Scavenger", fx:"On Reveal: +3 if a card was destroyed or discarded during the game."},
    ficelle:{n:"The Devouring Thread", fx:"On Reveal: destroy your other cards here. +3 for each."},
    ecorche:{n:"The Silent Flayed One", fx:"Can't be weakened. On Reveal: −2 to a random enemy card here."},
    promethee:{n:"Prometheus", fx:"Ongoing: the energy you don't spend carries over to the next turn (10 max)."},
    athena:{n:"Athena", fx:"On Reveal: put the most expensive of the top 3 cards of your deck into your hand."},
    bia:{fx:"On Reveal: your opponent loses their stored energy. If they had none, −1 to their strongest card here."},
    pandore:{n:"Pandora", fx:"On Reveal: spend all your remaining energy. +1 for each energy spent."},
    styx:{fx:"Ongoing: Nike and Bia have +3 wherever they are. Your Judgement cards here can't be destroyed."},
    nike:{fx:"On Reveal: +2 for each other card you played before her this turn. Requires 8 Judgement cards in the deck, Nike included."},
    ulya:{fx:"Costs 1 less for each other card in your hand. On Reveal: +1 for each card left in your hand. Requires Yarden Weiss and Apsu in the deck."},
    morrigan_h:{n:"Morrigan, Halloween Witch", fx:"On Reveal: draw 2 cards, then discard the most expensive card in your hand."},
    nyx_h:{n:"Nyx, Halloween Warrior", fx:"On Reveal: destroy the 2 weakest enemy cards here."},
    izzy_h:{n:"Izzy, Blood Moon", fx:"On Reveal: destroy the strongest enemy card here (6 or less) and gain half its Power, rounded up."},
    yarden_d:{n:"Yarden, Partial Dragonification", fx:"Ongoing: +2 for each other Primordial card on your side. On Reveal: if Yarden Weiss is on your side, she is destroyed and you gain her Power."},
    ares_h:{n:"Ares, Halloween Butcher", fx:"On Reveal: −2 to each enemy card here, and +1 for each."},
    nergal_h:{n:"Nergal, Halloween Gravedigger", fx:"On Reveal: the plague takes every other card with 1 Power or less, on both sides and in all 3 locations. +2 for each."},
    aphrodite_n:{n:"Aphrodite, Christmas Star", fx:"On Reveal: leave a 3-Power Reflection of Aphrodite in each of your other locations."},
    sekhmet_n:{n:"Sekhmet, Winter Lioness", fx:"On Reveal: destroy enemy cards here with 2 Power or less. Yours are spared."},
    calypso_n:{n:"Calypso, Ice Queen", fx:"On Reveal: the strongest enemy card here becomes captive (0 while Calypso stays in play). +1 for each enemy card here."},
    apsu_n:{n:"Apsu, Vigil of Chains", fx:"On Reveal: enemy cards here lose their effects. Your next card costs 2 less. +4 if Yarden Weiss is on your side."},
    joanna:{n:"Lady Joanna", fx:"On Reveal: leave a 2-Power Lantern in each of your other locations where you already have a card."},
    ulji:{fx:"On Reveal: take the most powerful card from the enemy hand and summon it here, or in another location if this one is full. Requires Jordan and Izzy in the deck."},
    mendiant:{n:"The Riponne Beggar", fx:"On Reveal: discard a random card from your hand. Feeds Rémi."},
    voleuse:{n:"The Flon Thief", fx:"On Reveal: your opponent discards a random card from their hand."},
    messagere:{n:"Hecate's Messenger", fx:"On Reveal: +3 if you have 4 or more cards in hand."},
    mouche:{n:"The Rift Fly", fx:"Ongoing: −1 to your other cards here."},
    sansvoix:{n:"The Voiceless", fx:"On Reveal: your opponent can't play here next turn."},
    dante:{fx:"On Reveal: +3 if a card was destroyed during the game."},
    fange:{n:"Mire", fx:"Ongoing: +1 for each card discarded during the game, on both sides."},
    chasseur:{n:"The Echo Hunter", fx:"On Reveal: create on your side an Echo of the strongest enemy card here (same Power, no effect)."},
    set:{fx:"On Reveal: the sandstorm scatters enemy cards from here to the other locations, at random, if there is room."},
    maree:{n:"Lord of the Black Tide", fx:"On Reveal: destroy enemy cards here that cost 2 or less."},
    brigid:{fx:"On Reveal: the next card you reveal gains +3."},
    lipdentelle:{n:"Lace Lip", fx:"On Reveal: discard the most expensive card in your hand and gain its Power."},
    andraste:{fx:"On Reveal: +2 for each enemy card here."},
    aphrodite:{fx:"On Reveal: leave a 2-Power Reflection of Aphrodite in each of your other locations."},
    calypso:{fx:"On Reveal: the strongest enemy card here becomes captive. Its Power drops to 0 while Calypso stays in play."},
    tefnut:{fx:"On Reveal: +1 to your other cards here."},
    susanoo:{fx:"On Reveal: move the strongest enemy card here to another location. +2 if Amaterasu is on your side."},
    chernobog:{fx:"Ongoing: enemy cards here can't go above their base Power."},
    bourreau:{n:"The Breach Executioner", fx:"On Reveal: seal an enemy slot here until the end of the game."},
    anubis:{fx:"On Reveal: weighs the hearts. If your opponent is winning here, destroy their strongest card here. Otherwise, +4."},
    balor:{fx:"On Reveal: −3 to every enemy card here."},
    nemesis:{fx:"Ongoing: at this location, the player with less Power wins. Two Nemesis cancel each other out."},
    ulaph:{fx:"On Reveal: the strongest enemy card here switches to your side. Requires Aphrodite and Yarden Weiss in the deck."},
    ulcal:{fx:"Ongoing: your cards here can be neither destroyed nor weakened, and the others gain +2. Requires Calypso and Jordan in the deck."},
    ulnem:{fx:"On Reveal: destroy the strongest card on each side here, then your other cards here gain +2. Requires Nemesis and Jordan in the deck."},
    hermes:{n:"Hermes", fx:"On Reveal: move your strongest card here to a revealed location it would win you."},
    konohana:{n:"Konohanasakuya-hime", fx:"At the end of the turn after she arrives, drops to 0: the blossom has passed."},
    mohini:{fx:"On Reveal: the strongest enemy card here loses its effects."},
    melinoe:{n:"Melinoe", fx:"On Reveal: discard a random card from your hand, then +3. Empty hand: no bonus."},
    biblio:{n:"The Passages Librarian", fx:"On Reveal: draw 1 card if you have fewer cards in hand than your opponent."},
    comptable:{n:"The Grand-Pont Accountant", fx:"On Reveal: +1 for each other card of yours here."},
    relieur:{n:"The Bookbinder", fx:"On Reveal: restore your weakest weakened card here to its base Power."},
    funambule:{n:"The Belvédère Tightrope Walker", fx:"On Reveal: +2 if it's your only card here."},
    tyr:{n:"Tyr", fx:"On Reveal: −1 to each enemy card here with 4 Power or more."},
    medee:{n:"Medea", fx:"On Reveal: \u22122 to the strongest enemy card here. +2 if Hecate is on your side."},
    medee_h:{n:"Medea, Spectral Bride", fx:"On Reveal: poison the strongest enemy card here: it loses 1 at the end of each turn, down to 0. If Hecate is on your side, also poison the second strongest."},
    carillonneur:{n:"The Cathedral Bell-Ringer", fx:"Ongoing: at the end of each turn, +1. End of turn 6: the knell tolls, your other cards here gain half his Power (rounded down)."},
    boucher:{n:"The Riponne Butcher", fx:"On Reveal: discard a random card from your hand."},
    tatoueur:{n:"The Chauderon Tattooist", fx:"On Reveal: your strongest card here gains +1 and can no longer be weakened."},
    graffeur:{n:"The Borde Tunnel Graffiti Artist", fx:"Ongoing: +2 on your side at the neighbouring locations."},
    odin:{fx:"On Reveal: discard the most expensive card in your hand, then draw 2 cards."},
    thor:{fx:"On Reveal: throw Mjölnir (a 2-Power token) to another location. If Mjölnir is destroyed, Thor gains +2."},
    heimdall:{fx:"On Reveal: your other cards here cross the Bifröst to a location where no one can play anymore, if there is room. Otherwise, +2."},
    hel:{fx:"On Reveal: resurrect your discarded cards at random locations, at base Power, without On Reveal."},
    dionysos:{fx:"On Reveal: each player draws 1 card, then discards a random card."},
    poseidon:{n:"Poseidon", fx:"On Reveal: the ebb tide returns enemy cards here that cost 3 or less to your opponent's hand."},
    hades:{n:"Hades", fx:"On Reveal: resurrect here your strongest destroyed card, without On Reveal."},
    circe:{n:"Circe", fx:"On Reveal: enemy cards here with 3 Power or less become Swine (1 Power, no effect)."},
    qetesh:{fx:"On Reveal: the strongest enemy card here (4 or less) is charmed. Its Power counts for you, but it stays on its side."},
    oshun:{fx:"On Reveal: +1 to all your other cards, in all 3 locations."},
    scathach:{fx:"On Reveal: leave a Shadow of Scáthach (\u22123 Power, no effect) on the enemy side, at another location."},
    loviatar:{fx:"On Reveal: resurrect here your last discarded card. It comes back sick: without On Reveal and with \u22122."},
    baldur:{fx:"Enemy effects can neither destroy nor weaken him, except those of cards costing 2 or less (the mistletoe) and those where \u201cnothing protects it\u201d."},
    ulcirce:{n:"Nyx X Circe", fx:"On Reveal: enemy cards here become Swine. Requires Nyx and Circe in the deck."},
    uloshun:{fx:"On Reveal: destroy the strongest enemy card here, then +2 to your weakest card in each location. Requires Nyx and Oshun in the deck."},
    ulqetjor:{fx:"Ongoing: your other cards have +1, in all 3 locations. Requires Qetesh and Jordan in the deck."},
    ulqetyar:{fx:"Ongoing: +3 for each location where you have both a Desire card and a Primordial card. Requires Qetesh and Yarden Weiss in the deck."},
    ulhel:{n:"Hel X Baldur", fx:"On Reveal: resurrect your discarded cards at random locations, without On Reveal. They can be neither destroyed nor weakened. Requires Hel and Baldur in the deck."},
    hel_r:{n:"Hel, New Year's Eve Queen", fx:"On Reveal: resurrect here your most expensive discarded card, with its On Reveal."},
    eos_r:{n:"Eos of the New Year", fx:"On Reveal: draw 1 card, 2 if Persephone is on your side. Your next card costs 1 less."},
    pele_r:{n:"Pele of New Year's Eve", fx:"On Reveal: the fireworks burst in all 3 locations. −2 to the strongest enemy card in each location."},
    qetesh_r:{n:"Qetesh of the New Year", fx:"On Reveal: the strongest enemy card here (5 or less) is charmed. +1 to your other cards here."},
    ulpele_r:{n:"Pele X Jordan of New Year's Eve", fx:"On Reveal: the lava deals −1 to every enemy card, in all 3 locations. Requires Pele and Jordan in the deck."},
    ulqetjor_r:{n:"Qetesh X Jordan of the New Year", fx:"Ongoing: your other cards have +1, in all 3 locations. On Reveal: charm the strongest enemy card in each location (3 or less). Requires Qetesh of the New Year and Jordan in the deck."},
    reflet:{n:"Reflection", fx:"Token left by Lake Ouchy."},
    illusion:{n:"Illusion", fx:"Token left by Kitsune."},
    lanterne:{n:"Lantern", fx:"Token left by Lady Joanna."},
    cendreux:{n:"Ashling", fx:"Token left by the Mother of Ash."},
    refaph:{n:"Reflection of Aphrodite", fx:"Token left by Aphrodite."},
    mjolnir:{fx:"Token thrown by Thor. If it is destroyed, Thor gains +2."},
    ombre:{n:"Shadow of Scáthach", fx:"Token left by Scáthach on the enemy side."},
    pourceau:{n:"Swine", fx:"A card turned into Swine by Circe."}
  },
  locs: {
    ouchy:{n:"Lake Ouchy", fx:"The first card each player plays here leaves a 2-Power Reflection."},
    sousgare:{n:"Underground, 4B", fx:"Félix gives credit: cards played here cost 1 less."},
    ruelle:{n:"The Alley", fx:"Where it all began. 2 cards maximum per player."},
    tour:{n:"Ouchy, 16th Floor", fx:"Izzy's place: cards with base Power 5+ have +2 here."},
    faille:{n:"The Rift", fx:"End of turn 4: destroy the weakest card on each side. Protected cards (Eir, Ame-no-Uzume, Baldur) resist it."},
    domaine:{n:"The Creator's Domain", fx:"Cards that form a Fusion with Jordan have +2 here."},
    tombeau:{n:"The Tomb", fx:"End of turn 6: each player summons here their discarded cards, at random, while there is room."},
    archives:{n:"Archives of Thoth", fx:"When you play a card here, draw 1 card."},
    cathedrale:{n:"Helvara Cathedral", fx:"The gods are watching: the side with fewer cards here gets +3."}
  }
};
