/* Duel d'Helvara : interface en anglais.
   - data   : tables du jeu remplacées en anglais (rangs, mois, quêtes, packs, saisons…)
   - exact  : texte affiché identique → traduction
   - rules  : textes qui contiennent des nombres ou des noms, traduits par motif
   Le jeu ne touche à rien de tout ça en français. */
(function(){
  const s=(n,w,p)=>(+n>1||+n===0&&false)?(p||w+"s"):w;               /* pluriel anglais */
  const who=w=>w==="L'adversaire"?"The opponent":w;
  const rec=v=>v===undefined?"":v;

  /* Notes d'effet, entre parenthèses dans le journal */
  const NOTES=[
    [/^dépense (\d+) énergie, \+(\d+)$/, (m,a,b)=>`spends ${a} energy, +${b}`],
    [/^prend (.+) en main$/, (m,a)=>a==="une carte"?"takes a card into hand":`takes ${a} into hand`],
    [/^l'adversaire perd son énergie conservée$/, ()=>"the opponent loses their stored energy"],
    [/^\+1 à (.+), encre indélébile$/, (m,a)=>`+1 to ${a}, permanent ink`],
    [/^défausse (.+), pioche 2$/, (m,a)=>`discards ${a}, draws 2`],
    [/^\+1 énergie au prochain tour$/, ()=>"+1 energy next turn"],
    [/^ajoute (.+) à sa main$/, (m,a)=>`adds ${a} to hand`],
    [/^l'effet du lieu s'arrête$/, ()=>"the location's effect stops"],
    [/^la forge s'allume$/, ()=>"the forge lights up"],
    [/^le lieu est verrouillé$/, ()=>"the location is locked"],
    [/^pioche (\d+) cartes?$/, (m,n)=>`draws ${n} ${s(n,"card")}`],
    [/^pioche 2, défausse (.+)$/, (m,a)=>`draws 2, discards ${a}`],
    [/^pioche (\d+)$/, (m,n)=>`draws ${n}`],
    [/^prochaine carte −(\d+)$/, (m,n)=>`next card −${n}`],
    [/^silence au prochain tour$/, ()=>"silenced next turn"],
    [/^tout revient à la base$/, ()=>"everything returns to base"],
    [/^une case adverse est condamnée$/, ()=>"an enemy slot is sealed"],
    [/^(\d+) cartes? sans effet$/, (m,n)=>`${n} ${s(n,"card")} lose their effects`],
    [/^(.+) est défaussée, plus de place$/, (m,a)=>`${a} is discarded, no room left`],
    [/^(.+) devient une carte de puissance 1$/, (m,a)=>`${a} becomes a 1-Power card`],
    [/^(.+) est captive$/, (m,a)=>`${a} is captive`],
    [/^(.+) est détruite$/, (m,a)=>`${a} is destroyed`],
    [/^(.+) est protégée$/, (m,a)=>`${a} is protected`],
    [/^(.+) part vers (.+)$/, (m,a,b)=>`${a} goes to ${b}`],
    [/^(\d+) Cendreux$/, (m,n)=>`${n} ${s(n,"Ashling")}`],
    [/^(\d+) Lanternes?$/, (m,n)=>`${n} ${s(n,"Lantern")}`],
    [/^(\d+) Reflets? d'Aphrodite( \(3\))?$/, (m,n,x)=>`${n} ${s(n,"Reflection")} of Aphrodite${rec(x)}`],
    [/^\+(\d+) à (\d+) cartes?$/, (m,v,n)=>`+${v} to ${n} ${s(n,"card")}`],
    [/^\+(\d+) à (.+)$/, (m,v,a)=>`+${v} to ${a}`],
    [/^absorbe (.+), \+(\d+)$/, (m,a,v)=>`absorbs ${a}, +${v}`],
    [/^copie (-?\d+)$/, (m,v)=>`copies ${v}`],
    [/^reflète (-?\d+)$/, (m,v)=>`reflects ${v}`],
    [/^disperse (\d+) cartes?$/, (m,n)=>`scatters ${n} ${s(n,"card")}`],
    [/^défausse (.+), \+(\d+)$/, (m,a,v)=>`discards ${a}, +${v}`],
    [/^défausse (.+)$/, (m,a)=>`discards ${a}`],
    [/^(.+) défausse (.+)$/, (m,w,a)=>`${who(w)} discards ${a}`],
    [/^détruit (.+), pioche 1$/, (m,a)=>`destroys ${a}, draws 1`],
    [/^rejoue (\d+) cartes?$/, (m,n)=>`replays ${n} ${s(n,"card")}`],
    [/^rejoue (.+)$/, (m,a)=>`replays ${a}`],
    [/^détruit (\d+) cartes?, \+(\d+)$/, (m,n,v)=>`destroys ${n} ${s(n,"card")}, +${v}`],
    [/^détruit (\d+) cartes?$/, (m,n)=>`destroys ${n} ${s(n,"card")}`],
    [/^détruit (.+) \(\+(\d+)\)$/, (m,a,v)=>`destroys ${a} (+${v})`],
    [/^détruit (.+), \+(\d+)$/, (m,a,v)=>`destroys ${a}, +${v}`],
    [/^détruit (.+)$/, (m,a)=>`destroys ${a}`],
    [/^invoque (.+)$/, (m,a)=>`summons ${a}`],
    [/^justice : (\d+) cartes? détruites?$/, (m,n)=>`justice: ${n} ${s(n,"card")} destroyed`],
    [/^la peste emporte (\d+) cartes?, \+(\d+)$/, (m,n,v)=>`the plague takes ${n} ${s(n,"card")}, +${v}`],
    [/^le cœur est trop lourd : détruit (.+)$/, (m,a)=>`the heart is too heavy: destroys ${a}`],
    [/^purifie (\d+) cartes?, \+(\d+)$/, (m,n,v)=>`purifies ${n} ${s(n,"card")}, +${v}`],
    [/^séduit (.+)$/, (m,a)=>`seduces ${a}`],
    [/^Écho (?:d’|de )(.+) \((-?\d+)\)$/, (m,a,v)=>`Echo of ${a} (${v})`],
    [/^−(\d+) à (\d+) cartes?$/, (m,v,n)=>`−${v} to ${n} ${s(n,"card")}`],
    [/^−(\d+) à (\d+), \+(\d+)$/, (m,v,n,b)=>`−${v} to ${n}, +${b}`],
    [/^−(\d+) à (.+)$/, (m,v,a)=>`−${v} to ${a}`],
    [/^paiera au tour (\d+)$/, (m,t)=>`will pay on turn ${t}`],
    [/^ne sera jamais payé$/, ()=>"will never be paid"],
    [/^en fleur jusqu'au prochain tour$/, ()=>"in bloom until next turn"],
    [/^Mjölnir → (.+)$/, (m,a)=>`Mjölnir → ${a}`],
    [/^Ombre → (.+)$/, (m,a)=>`Shadow → ${a}`],
    [/^(\d+) cartes? passen?t? par le Bifröst$/, (m,n)=>`${n} ${s(n,"card")} cross the Bifröst`],
    [/^ressuscite (\d+) cartes?, intouchables$/, (m,n)=>`resurrects ${n} ${s(n,"card")}, untouchable`],
    [/^ressuscite (\d+) cartes?$/, (m,n)=>`resurrects ${n} ${s(n,"card")}`],
    [/^ressuscite (.+)$/, (m,a)=>`resurrects ${a}`],
    [/^(.+) revient malade \(−2\)$/, (m,a)=>`${a} comes back sick (−2)`],
    [/^l'ivresse fait défausser (.+) et (.+)$/, (m,a,b)=>`drunkenness makes them discard ${a} and ${b}`],
    [/^l'ivresse fait défausser (.+)$/, (m,a)=>`drunkenness makes them discard ${a}`],
    [/^pioche 1$/, ()=>"draws 1"],
    [/^le reflux emporte (\d+) cartes?$/, (m,n)=>`the ebb tide takes ${n} ${s(n,"card")}`],
    [/^(\d+) Pourceaux?$/, (m,n)=>`${n} Swine`],
    [/^charme (\d+) cartes?$/, (m,n)=>`charms ${n} ${s(n,"card")}`],
    [/^charme (.+)$/, (m,a)=>`charms ${a}`],
    [/^empoisonne (.+) et (.+)$/, (m,a,b)=>`poisons ${a} and ${b}`],
    [/^empoisonne (.+)$/, (m,a)=>`poisons ${a}`],
    [/^(.+) perd ses effets$/, (m,a)=>`${a} loses its effects`]
  ];
  function note(t){
    for(const [re,f] of NOTES){ const m=t.match(re); if(m) return f(...m); }
    const i=t.lastIndexOf(", ");                                       /* « A, B » : on traduit chaque moitié */
    if(i>0){ const a=note(t.slice(0,i)), b=note(t.slice(i+2)); if(a!==t.slice(0,i)||b!==t.slice(i+2)) return a+", "+b; }
    return t;
  }

  const exact={
    /* en-tête, menus */
    "Le Sang de Tiamat":"The Blood of Tiamat", "Accueil":"Home", "Collection":"Collection", "Boutique":"Shop", "Classement":"Rankings",
    "← Accueil":"← Home", "Règles":"Rules", "Voir mon profil":"View my profile", "Fermer":"Close", "Annuler":"Cancel", "Enregistrer":"Save",
    "OK":"OK", "Valider":"Confirm", "Continuer":"Continue", "Terminer":"Finish", "Plus tard":"Later", "Changer":"Change",
    /* accueil */
    "Nouveau":"New", "Bientôt disponible":"Coming soon", "Voir la collection":"View the collection",
    "Glisse pour faire tourner":"Swipe to rotate", "Choisir mes cartes":"Choose my cards", "Jouer":"Play",
    "Reprendre le duel":"Resume the duel", "Reprendre la partie":"Resume the game",
    "Première partie : la Ruelle, le Lac Ouchy et le Sous-gare.":"First game: the Alley, Lake Ouchy and the Underground.",
    "Ouvre la Première Brûlure à la boutique pour obtenir ton premier deck.":"Open the First Burn in the shop to get your first deck.",
    "Blitz":"Blitz", "Duel entre amis":"Duel with friends", "Ta partie gratuite du jour t'attend · jusqu'à 300 CHF":"Your free daily game is waiting · up to 300 CHF",
    "Un duel peut être repris":"A duel can be resumed", "Crée un salon":"Create a room", "Partie gratuite du jour":"Free game today", "Réglages":"Settings", "Langue":"Language", "Son":"Sound", "Tutoriel":"Tutorial", "Menu":"Menu", "Crée un salon et partage le code":"Create a room and share the code",
    "Quêtes du jour":"Daily quests", "Récompense récupérée":"Reward claimed", "Récupérer":"Claim",
    "Progression sauvegardée pour cet appareil.":"Progress saved on this device.", "Progression sauvegardée sur cet appareil.":"Progress saved on this device.",
    "Se connecter avec Google":"Sign in with Google", "pour la retrouver partout.":"to keep it everywhere.", "Se déconnecter":"Sign out",
    "Revoir le tutoriel":"Replay the tutorial", "Volume de la musique":"Music volume", "Volume des effets":"Sound effects volume", "Quête de la semaine":"Weekly quest", "Gagne 15 parties cette semaine":"Win 15 games this week", "Jusqu'à dimanche soir":"Until Sunday night", "Tu peux changer une quête par jour.":"You can change one quest per day.", "Cinématiques":"Cinematics", "Activée":"On", "Coupée":"Off", "Touche pour passer":"Tap to skip", "Musique : activée":"Music: on", "Musique : coupée":"Music: off", "Effets : activés":"Sound effects: on", "Effets : coupés":"Sound effects: off",
    "Vitrine : glisse pour faire tourner les cartes":"Showcase: swipe to rotate the cards",
    /* tutoriel */
    "Tutoriel":"Tutorial", "Bienvenue à Helvara":"Welcome to Helvara", "Chaque duel se joue sur":"Each duel is played across", "3 lieux":"3 locations",
    "et dure":"and lasts", "6 tours":"6 turns", ". Pour gagner, il faut avoir plus de puissance que l'adversaire sur":". To win, you need more Power than your opponent at",
    "2 lieux sur 3":"2 locations out of 3", "La partie guidée t'apprend tout en 5 minutes, carte par carte.":"The guided game teaches you everything in 5 minutes, card by card.",
    "La partie guidée t'apprend tout en 5 minutes, carte par carte. Dans les deux cas, tu reçois":"The guided game teaches you everything in 5 minutes, card by card. Either way, you receive",
    "Dans les deux cas, tu reçois":"Either way, you receive", "pour ton premier deck.":"for your first deck.",
    "Faire la partie guidée":"Play the guided game", "Passer le tutoriel":"Skip the tutorial", "Partie guidée":"Guided game",
    "Tu as":"You have", "1 énergie":"1 energy", "au tour 1. Touche le":"on turn 1. Tap the", "(coût 1), puis la":"(cost 1), then the",
    ". Termine ton tour : à la révélation, il te fait piocher une carte.":". End your turn: when revealed, it makes you draw a card.",
    "Le":"The", "vient d'apparaître. Chaque lieu a sa règle : ici, ta première carte laisse un Reflet de 2. Pose":"has just appeared. Each location has its own rule: here, your first card leaves a 2-Power Reflection. Play",
    "au Lac Ouchy : ta prochaine carte coûtera 1 de moins.":"at Lake Ouchy: your next card will cost 1 less.",
    "Céleste coûte 3, mais Félix et le":"Céleste costs 3, but Félix and the", "la font passer à 1. Pose":"bring her down to 1. Play",
    "au Sous-gare, puis la":"at the Underground, then the", "à la Ruelle. Tu peux jouer plusieurs cartes tant que tu as de l'énergie.":"at the Alley. You can play several cards as long as you have energy.",
    "L'Agent de Thot adverse a":"The enemy Agent of Thoth has", "affaibli":"weakened",
    "Céleste : son chiffre est passé en rouge. Pose":"Céleste: her number turned red. Play",
    "au Lac Ouchy : elle copie la puissance de la carte adverse la plus forte du lieu. Appui long sur une carte pour la voir en grand.":"at Lake Ouchy: she copies the Power of the strongest enemy card there. Long-press a card to see it full-size.",
    "Tu as des cartes dans les 3 lieux :":"You have cards in all 3 locations:", "gagne +4 en arrivant. Pose-la au Sous-gare.":"gains +4 on arrival. Play her at the Underground.",
    "Dernier tour. Pose le":"Last turn. Play the", "au Lac Ouchy. À la fin, celui qui mène sur 2 lieux sur 3 gagne.":"at Lake Ouchy. At the end, whoever leads at 2 locations out of 3 wins.",
    "C'est bon : touche":"All set: tap", "Fin du tour":"End turn",
    "Tu connais maintenant l'essentiel : l'énergie, les lieux, la révélation, les bonus en vert et les malus en rouge.":"You now know the essentials: energy, locations, reveals, bonuses in green and penalties in red.",
    "Recevoir 100 CHF et aller à la boutique":"Get 100 CHF and go to the shop", "Tutoriel terminé":"Tutorial complete",
    /* profil */
    "Joueur d'Helvara":"Player of Helvara", "Changer de nom":"Change name", "Changer d'avatar":"Change avatar", "Ton nom":"Your name",
    "Victoires":"Wins", "Défaites":"Losses", "Égalités":"Draws", "Ces chiffres comptent les parties classées de la saison.":"These numbers count this season's ranked games.",
    "Aucune partie enregistrée pour l'instant. Les 5 dernières apparaîtront ici.":"No games recorded yet. Your last 5 will appear here.",
    "Historique":"History", "Les 5 dernières parties":"Last 5 games", "Classé":"Ranked", "Duel":"Duel",
    "Victoire":"Victory", "Défaite":"Defeat", "Égalité":"Draw", "à l'instant":"just now",
    "Avatar":"Avatar",
    /* collection */
    "12/12 · actif":"12/12 · active", "Renommer":"Rename", "Changer l'illustration":"Change the art", "Nom du deck":"Deck name",
    "Toutes":"All", "Dans le deck":"In the deck", "À trouver dans un pack":"Found in packs", "Bientôt":"Soon",
    "Touche une carte pour l'ajouter au deck ou l'en retirer, garde le doigt dessus pour la voir en grand. Les cartes grisées restent à trouver.":"Tap a card to add it to the deck or remove it, hold your finger on it to see it full-size. Greyed-out cards are still to be found.",
    "Aucune carte de cette faction pour l'instant.":"No cards from this faction yet.", "Jouer avec ce deck":"Play with this deck",
    "Les lieux d'Helvara":"The locations of Helvara", "Trois lieux par partie, révélés aux tours 1, 2 et 3.":"Three locations per game, revealed on turns 1, 2 and 3.",
    "Touche une carte pour l'agrandir.":"Tap a card to enlarge it.", "Ton deck est plein : retire d'abord une carte.":"Your deck is full: remove a card first.",
    "Ta vitrine":"Your showcase", "Cartes affichées":"Displayed cards", "En faire mon avatar":"Make it my avatar", "Choisir un avatar":"Choose an avatar",
    "Fusion disponible":"Fusion available", "Ultra-légendaire de faction":"Faction Ultra-Legendary", "Réclamer la carte":"Claim the card", "Ultra-légendaire":"Ultra-legendary",
    /* boutique */
    "Pack de départ · 12 cartes":"Starter pack · 12 cards", "Tu as déjà toutes les cartes de ces raretés":"You already own every card of these rarities",
    "Collection complète":"Collection complete", "Ouvre d'abord la Première Brûlure":"Open the First Burn first", "Acheter et ouvrir":"Buy and open",
    "Voilà tes 100 CHF. Achète la":"Here are your 100 CHF. Buy the", ": 12 cartes pour construire ton premier deck.":": 12 cards to build your first deck.",
    "Échoppe du jour":"Daily stall", "Déjà à toi":"Already yours", "Nouvelle":"New", "Voir mon deck":"View my deck", "Ajouter à mon deck":"Add to my deck",
    /* classement */
    "en ligne":"online", "Les joueurs en ligne apparaissent en direct. Les autres gardent le dernier rang enregistré.":"Online players appear live. Others keep their last recorded rank.",
    "Ta progression n'est pas sauvegardée sur ton compte : tu apparais quand tu es en ligne.":"Your progress isn't saved to your account: you appear while you are online.",
    "Personne n'a encore joué cette saison.":"No one has played this season yet.", "Pas encore vus cette saison":"Not seen yet this season",
    /* duel */
    "Chacun joue avec son deck. Les duels rapportent des CHF et comptent pour les quêtes, mais pas pour le rang.":"Each player uses their own deck. Duels earn CHF and count for quests, but not for rank.",
    "Créer un salon":"Create a room", "Rejoindre":"Join", "Code du salon":"Room code", "Inviter un ami":"Invite a friend",
    "Envoie-lui l'adresse de cette page.":"Send them this page's address.", "Il peut jouer tout de suite. En se connectant avec":"They can play right away. By signing in with",
    "Google":"Google", "(bas de l'accueil), il retrouve sa progression sur tous ses appareils.":"(bottom of the home screen), they keep their progress on all their devices.",
    "Il ouvre le lien, construit son deck, puis rejoint ton salon avec le code.":"They open the link, build their deck, then join your room with the code.",
    "Connexion au salon…":"Connecting to the room…", "Le salon en direct est injoignable pour l'instant. Vérifie ta connexion internet, puis recharge la page.":"The live room can't be reached right now. Check your internet connection, then reload the page.",
    "Reconnexion":"Reconnecting", "Retour dans le salon":"Back in room", "Abandonner le duel":"Forfeit the duel", "Complète d'abord ton deck de 12 cartes.":"Complete your 12-card deck first.",
    "Aller au deck":"Go to the deck", "Reprendre":"Resume", "Oublier":"Forget", "Salon":"Room", "En attente d'un adversaire. Envoie-lui le code.":"Waiting for an opponent. Send them the code.",
    "Ce salon est déjà complet.":"This room is already full.", "Connecté à":"Connected to", ". La partie commence…":". The game is starting…",
    "Salon introuvable pour l'instant. Vérifie le code, ou attends que ton ami le crée.":"Room not found yet. Check the code, or wait for your friend to create it.",
    "Copier le code":"Copy the code", "Quitter le salon":"Leave the room", "Copié":"Copied", "Revanche":"Rematch", "Abandonner":"Forfeit",
    "Connexion au salon perdue. Recharge la page.":"Lost connection to the room. Reload the page.", "Le code ressemble à OUCHY-4821.":"The code looks like OUCHY-4821.",
    "Duel entre amis · hors classement":"Duel with friends · unranked", "Quitter le duel":"Leave the duel",
    "déconnecté, en attente de son retour":"disconnected, waiting for them to return", "· a terminé son tour":"· has ended their turn",
    /* blitz */
    "Construis un deck sur le moment et enchaîne 3 matchs de plus en plus durs. Tu commences avec le Coursier du Flon, Félix, Céleste et Izzy, puis tu choisis 8 cartes, une parmi 4 à chaque fois. Toutes les cartes sorties peuvent apparaître, même celles que tu n'as pas. Pas d'ultra-légendaire.":"Build a deck on the spot and play 3 increasingly hard matches. You start with the Flon Courier, Félix, Céleste and Izzy, then pick 8 cards, one out of 4 each time. Every released card can appear, even ones you don't own. No ultra-legendaries.",
    "Une défaite termine le Blitz. Tu repars avec la récompense du palier atteint. Le Blitz ne compte pas pour ton rang.":"A loss ends the Blitz. You leave with the reward of the tier you reached. Blitz doesn't count toward your rank.",
    "Lancer le Blitz du jour · gratuit":"Start today's Blitz · free", "Une partie gratuite par jour.":"One free game per day.",
    "Blitz terminé":"Blitz over", "Aucune récompense":"No reward", "Choisis une carte. Appui sur une carte de ton deck pour la revoir.":"Pick a card. Tap a card in your deck to see it again.",
    "Ton deck":"Your deck", "Gagne pour décrocher ta première récompense.":"Win to earn your first reward.", "Reprendre le match":"Resume the match",
    "Jouer le match":"Play the match", "Adversaire de niveau":"Opponent level", "Blitz terminé, sans récompense":"Blitz over, no reward",
    "Égalité : le match est à rejouer":"Draw: the match will be replayed", "Voir le bilan":"View the summary", "Continuer le Blitz":"Continue the Blitz",
    /* règles */
    "Comment jouer":"How to play", "Le tutoriel complet est disponible à tout moment.":"The full tutorial is available at any time.",
    "6 tours. Au tour N, tu as N énergie. Tu pioches 1 carte par tour (main de 7 maximum).":"6 turns. On turn N, you have N energy. You draw 1 card per turn (7-card hand maximum).",
    "Tu poses tes cartes, l'adversaire pose les siennes face cachée. Tout est révélé en fin de tour, lieu par lieu : dans chaque lieu, le joueur qui mène révèle ses cartes en premier. En cas d'égalité, tes cartes d'abord (en duel, celles de l'hôte).":"You play your cards, your opponent plays theirs face down. Everything is revealed at the end of the turn, location by location: at each location, the player who is winning reveals first. On a tie, your cards go first (in a duel, the host's).",
    "4 cartes maximum par joueur et par lieu.":"4 cards maximum per player per location.",
    "Au tour 1, avant de poser une carte, tu peux":"On turn 1, before playing a card, you can", "changer ta main":"redraw your hand",
    "une fois : tes cartes repartent dans le deck, qui est mélangé, et tu en pioches autant. Pas en duel entre amis.":"once: your cards go back into the deck, which is shuffled, and you draw as many. Not in duels with friends.",
    "« Révélation » se déclenche une fois quand la carte se retourne. « Continu » agit tant que la carte est en jeu et n'a pas perdu ses effets. Une carte qui perd ses effets garde ce que sa Révélation lui a déjà donné.":"“On Reveal” triggers once when the card flips. “Ongoing” works as long as the card is in play and hasn't lost its effects. A card that loses its effects keeps what its On Reveal already gave it.",
    "« En jeu » veut dire révélée sur le plateau, de n'importe quel côté.":"“In play” means revealed on the board, on either side.",
    "À la fin du tour 6, remporte 2 lieux sur 3. En cas d'égalité, la puissance totale départage.":"At the end of turn 6, win 2 locations out of 3. On a tie, total Power decides.",
    "Vocabulaire":"Glossary", "Détruire":"Destroy",
    ": la carte quitte le plateau. Eir et Ame-no-Uzume l'empêchent, sauf si l'effet dit « rien ne la protège » : là, aucune protection ne tient.":": the card leaves the board. Eir and Ame-no-Uzume prevent it, unless the effect says “nothing protects it”: then no protection holds.",
    "Défausser":"Discard", ": la carte quitte ta main sans être jouée.":": the card leaves your hand without being played.",
    "Rémi et le Charognard du M2 comptent les cartes détruites":"Rémi and the M2 Scavenger count cards destroyed", "et":"and", "défaussées.":"discarded.",
    "Affaiblir":"Weaken",
    "(−X) : la carte perd de la puissance. La puissance peut devenir négative. Eir, Amaterasu, l'Écorché Silencieux et Jordan, le Créateur l'empêchent.":"(−X): the card loses Power. Power can go negative. Eir, Amaterasu, the Silent Flayed One and Jordan, the Creator prevent it.",
    "Perdre ses effets":"Lose its effects", ": la carte garde sa puissance et les bonus déjà gagnés, mais ses effets Continu et de fin de tour ne s'appliquent plus.":": the card keeps its Power and the bonuses it already gained, but its Ongoing and end-of-turn effects no longer apply.", "Ses effets Continu et de fin de tour ne s'appliquent plus. Ses bonus déjà gagnés restent.":"Its Ongoing and end-of-turn effects no longer apply. The bonuses it already gained stay.", "(acquis)":"(kept)",
    "Une seule ultra-légendaire par deck.":"Only one ultra-legendary per deck.", "Chaque fusion exige ses deux personnages dans le deck.":"Each fusion requires both of its characters in the deck.", "Une ultra-légendaire de faction, comme Nike, exige assez de cartes de sa faction.":"A faction ultra-legendary, like Nike, requires enough cards of its faction.",
    "Condamner":"Seal", ": une case du lieu est fermée pour l'adversaire jusqu'à la fin de la partie.":": a slot at the location is closed to the opponent until the end of the game.",
    "Captive":"Captive", ": la carte tombe à 0 tant que sa geôlière reste en jeu.":": the card drops to 0 while its jailer stays in play.",
    "Silence":"Silence", ": l'adversaire ne peut pas jouer dans ce lieu au tour suivant.":": the opponent can't play at this location next turn.",
    "Une seule version par personnage":"Only one version per character",
    "dans un deck (par exemple Nyx ou Nyx, Guerrière d'Halloween). Seule exception : la Dragonification de Yarden peut côtoyer Yarden Weiss.":"in a deck (for example Nyx or Nyx, Halloween Warrior). Only exception: Yarden's Dragonification can sit alongside Yarden Weiss.",
    "De ton côté":"On your side", ": uniquement tes cartes révélées.":": only your revealed cards.", "En jeu":"In play", ": n'importe quelle carte révélée, des deux côtés.":": any revealed card, on either side.",
    "Sur le plateau, le petit chiffre vert ou rouge indique l'écart avec la puissance de base. Appui long pour voir le détail.":"On the board, the small green or red number shows the difference from base Power. Long-press to see the details.",
    "Rangs et saisons":"Ranks and seasons", "Sept paliers :":"Seven tiers:",
    "Sept paliers : Passant → Initié → Agent → Élu → Héraut → Avatar → Divinité d'Helvara. Chacun a trois divisions (III, II, I). Il faut 3 étoiles par division en Passant et Initié, 4 en Agent et Élu, 5 en Héraut et Avatar.":"Seven tiers: Wanderer → Initiate → Agent → Chosen → Herald → Avatar → Deity of Helvara. Each has three divisions (III, II, I). You need 3 stars per division in Wanderer and Initiate, 4 in Agent and Chosen, 5 in Herald and Avatar.",
    "Victoire : +1 étoile, +2 à partir de 2 victoires d'affilée (jusqu'à Héraut). Défaite : −1 étoile, sauf en Passant et Initié où elle ne coûte rien. Égalité : rien ne bouge.":"Win: +1 star, +2 from 2 wins in a row (up to Herald). Loss: −1 star, except in Wanderer and Initiate where it costs nothing. Draw: nothing changes.",
    "Le Serment":"The Oath",
    "(parties classées uniquement) : une fois par partie, jusqu'au tour 5, tu peux jurer sur un lieu révélé. Si tu le remportes avec la partie, tu gagnes 2 étoiles, série comprise. Si tu le perds (ou en cas d'égalité sans Morrigan), tu perds 1 étoile de plus, même si tu gagnes la partie.":"(ranked games only): once per game, up to turn 5, you can swear on a revealed location. If you win it along with the game, you earn 2 stars, streak included. If you lose it (or tie without Morrigan), you lose 1 more star, even if you win the game.",
    "Le début de chaque palier est un plancher : on ne redescend jamais sous un palier atteint pendant la saison.":"The start of each tier is a floor: you never drop below a tier reached during the season.",
    "Plus ton rang est haut, plus l'adversaire construit un deck solide et joue bien. Il n'utilise jamais une rareté que tu n'as pas encore trouvée.":"The higher your rank, the stronger the opponent's deck and play. It never uses a rarity you haven't found yet.",
    "Chaque mois, nouvelle saison : tu redescends de 3 paliers (une Divinité repart en Élu) et tu reçois 25 CHF par palier atteint (175 CHF pour la Divinité).":"Every month, a new season: you drop 3 tiers (a Deity restarts at Chosen) and receive 25 CHF per tier reached (175 CHF for a Deity).",
    /* partie */
    "Tour":"Turn", "énergie":"energy", "énergie ·":"energy ·", "⚖ Serment":"⚖ Oath", "Changer ma main":"Redraw my hand", "Révélation…":"Revealing…",
    "Nouvelle partie":"New game", "Lieu inconnu":"Unknown location", "Effet arrêté":"Effect stopped", "Verrouillé":"Locked",
    "Silence : tu ne peux pas jouer ici":"Silence: you can't play here", "Silence adverse":"Enemy silence", "Nemesis : le plus faible gagne":"Nemesis: the weakest wins",
    "Touche un lieu pour la poser.":"Tap a location to play it.", "Effets annulés.":"Effects cancelled.", "Effet arrêté par Perséphone.":"Effect stopped by Persephone.",
    "Touche une carte de ta main puis un lieu pour la poser.":"Tap a card in your hand, then a location to play it.", "Appui long":"Long-press",
    "sur une carte ou un lieu pour le voir en grand. Touche une carte posée ce tour pour la reprendre.":"a card or a location to see it full-size. Tap a card played this turn to take it back.",
    "Main vide.":"Empty hand.", "Puissance :":"Power:", "Cette carte a perdu ses effets.":"This card has lost its effects.",
    "Verrouillé par Vritra : plus personne ne peut y jouer.":"Locked by Vritra: no one can play here anymore.",
    "C'est définitif. Gagne ce lieu avec la partie : +2 étoiles. Perds-le : −1 étoile.":"This is final. Win this location and the game: +2 stars. Lose it: −1 star.",
    "Je le jure":"I swear it", "Une fois par partie, jusqu'au tour 5. Choisis un lieu révélé.":"Once per game, up to turn 5. Choose a revealed location.",
    "Victoire !":"Victory!", "Partie terminée":"Game over", "Rejouer":"Play again", "Voir le plateau":"View the board",
    "Serment tenu : +2 étoiles":"Oath kept: +2 stars", "Serment tenu, mais la partie est perdue":"Oath kept, but the game is lost", "Serment rompu : −1 étoile":"Oath broken: −1 star",
    "Promotion !":"Promotion!", "Rétrogradation":"Demotion", "+2 étoiles (série)":"+2 stars (streak)", "+1 étoile":"+1 star", "−1 étoile":"−1 star",
    "Passant et Initié : une défaite ne coûte rien":"Wanderer and Initiate: a loss costs nothing", "Plancher du palier : rien de perdu":"Tier floor: nothing lost",
    "Égalité : rang inchangé":"Draw: rank unchanged", "(Morrigan)":"(Morrigan)", "(Nemesis)":"(Nemesis)", "Aucune partie en cours.":"No game in progress.",
    "Main changée":"Hand redrawn",
    "⚖ L'adversaire jure sur":"⚖ The opponent swears on", ". Relever le défi ?":". Take up the challenge?", "Relever":"Accept", "Ignorer":"Ignore",
    "⚖ Serment croisé sur":"⚖ Cross Oath on", "⚖ L'adversaire a juré sur":"⚖ The opponent swore on",
    ": tout se joue sur ce lieu. Gagne-le avec la partie : +4 étoiles. Perds-le avec la partie : −4.":": everything rides on this location. Win it and the game: +4 stars. Lose it and the game: −4.",
    "⚖ Serment croisé":"⚖ Cross Oath", "⚖ Serment adverse":"⚖ Enemy Oath", "⚖ Serment":"⚖ Oath",
    "Serment croisé, c'est définitif. Lieu et partie gagnés : +4 étoiles. Lieu et partie perdus : −4. Sinon : 0.":"Cross Oath, this is final. Location and game won: +4 stars. Location and game lost: −4. Otherwise: 0.",
    "Serment croisé tenu : +4 étoiles":"Cross Oath kept: +4 stars", "Serment croisé tenu, mais la partie est perdue":"Cross Oath kept, but the game is lost",
    "Serment croisé perdu : ta victoire ne rapporte aucune étoile":"Cross Oath lost: your win earns no stars", "Serment croisé perdu : −4 étoiles":"Cross Oath lost: −4 stars", "Serment croisé tenu : ta défaite ne coûte rien":"Cross Oath kept: your loss costs nothing",
    "Serment croisé tenu":"Cross Oath kept", "Serment croisé perdu":"Cross Oath lost", "Aucune étoile perdue":"No stars lost", "−4 étoiles (serment croisé)":"−4 stars (Cross Oath)",
    "+4 étoiles (serment croisé)":"+4 stars (Cross Oath)", "Aucune étoile gagnée":"No stars earned",
    "Serment adverse":"Enemy Oath", "Serment croisé":"Cross Oath",
    ": l'adversaire peut lui aussi jurer sur un lieu, entre les tours 2 et 4. Tu peux relever le défi en jurant sur le même lieu : c'est le":": the opponent can also swear on a location, between turns 2 and 4. You can take up the challenge by swearing on the same location: that's the",
    ". Lieu et partie gagnés : +4 étoiles, série comprise. Lieu et partie perdus : −4 étoiles (jamais sous le plancher du palier). Lieu gagné mais partie perdue, ou l'inverse : 0.":". Location and game won: +4 stars, streak included. Location and game lost: −4 stars (never below the tier floor). Location won but game lost, or the reverse: 0.", "Vasseur (paiement)":"Vasseur (payment)", "Floraison passée":"Blossom passed", "Le Tatoueur":"The Tattooist", "Le glas":"The knell", "Loviatar":"Loviatar", "Mjölnir":"Mjölnir",
    "Main adverse :":"Enemy hand:", "Défausses :":"Discards:", "Cimetières :":"Graveyards:", "Cimetières":"Graveyards", "Défausses":"Discards", "Vide.":"Empty.", "Les cartes détruites. Touche une carte pour la lire.":"Destroyed cards. Tap a card to read it.", "Les cartes défaussées depuis la main. Touche une carte pour la lire.":"Cards discarded from hand. Tap a card to read it.",
    "Ressusciter":"Resurrect", ": une carte défaussée ou détruite revient sur le plateau, révélée, à sa puissance de base, sans déclencher sa Révélation (sauf mention contraire).":": a discarded or destroyed card comes back to the board, revealed, at base Power, without triggering its On Reveal (unless stated otherwise).",
    "Charmer":"Charm", ": la carte reste du côté adverse, mais sa puissance compte pour toi.":": the card stays on the enemy side, but its Power counts for you.", "Le Relieur":"The Bookbinder", "Brigid":"Brigid", "Idunn":"Idunn", "Ishtar":"Ishtar",
    "Te déconnecter ? Ta progression reste sur ton compte Google.":"Sign out? Your progress stays on your Google account.",
    "Supabase n'est pas configuré : le jeu tourne hors ligne.":"Supabase isn't configured: the game runs offline."
  };

  const rules=[
    /* accueil, profil */
    [/^Le Sang de Tiamat · (.+)$/, (m,a)=>`The Blood of Tiamat · ${a}`],
    [/^Effet arrêté par Perséphone\. (.*)$/, (m,a)=>`Effect stopped by Persephone. ${a}`],
    [/^Connexion du jour : \+(\d+) CHF \(jour (\d) sur 7, le 7e rapporte 50 CHF\)\.$/, (m,g,d)=>`Daily login: +${g} CHF (day ${d} of 7, day 7 pays 50 CHF).`],
    [/^7e jour d'affilée : \+(\d+) CHF !$/, (m,g)=>`7th day in a row: +${g} CHF!`],
    [/^Nouvelle saison ! Tu as fini au rang (.+) \(\+(\d+) CHF\) et tu reprends à (.+)\.$/, (m,a,g,b)=>`New season! You finished at ${a} (+${g} CHF) and restart at ${b}.`],
    [/^Nouvelle collection : (\d+) cartes? provisoires? remboursées? \(\+(\d+) CHF\)\.$/, (m,n,g)=>`New collection: ${n} temporary ${s(n,"card")} refunded (+${g} CHF).`],
    [/^(\d+) nouvelles cartes sont arrivées à Helvara$/, (m,n)=>`${n} new cards have arrived in Helvara`],
    [/^(\d+) nouvelles cartes le (.+)$/, (m,n,d)=>`${n} new cards on ${d}`],
    [/^Nouvelles quêtes dans (\d+) h$/, (m,h)=>`New quests in ${h} h`],
    [/^Nouvelle sélection dans (\d+) h$/, (m,h)=>`New selection in ${h} h`],
    [/^En cours · (\d) victoires? sur 3$/, (m,n)=>`In progress · ${n} ${s(n,"win")} out of 3`],
    [/^Prochaine partie gratuite dans (\d+) h · (\d+) CHF$/, (m,h,p)=>`Next free game in ${h} h · ${p} CHF`],
    [/^Gratuit dans (\d+) h$/, (m,h)=>`Free in ${h} h`],
    [/^En cours contre (.+?)((?: · \d+ V · \d+ D · \d+ É)?)$/, (m,a,r)=>`In progress against ${a}${vde(r)}`],
    [/^Duel en cours contre (.+?)((?: · \d+ V · \d+ D · \d+ É)?)$/, (m,a,r)=>`Duel in progress against ${a}${vde(r)}`],
    [/^(Crée un salon et partage le code|Crée un salon|Un duel peut être repris)( · \d+ V · \d+ D · \d+ É)$/, (m,a,r)=>exact[a]+vde(r)],
    [/^Cette saison : (\d+) % de victoires$/, (m,p)=>`This season: ${p}% wins`],
    [/^Ton deck a (\d+) cartes? sur 12\. Complète-le dans la Collection pour jouer\.$/, (m,n)=>`Your deck has ${n} ${s(n,"card")} out of 12. Complete it in the Collection to play.`],
    [/^Progression sauvegardée sur ton compte Google(?: \((.+)\))?\.$/, (m,e)=>`Progress saved to your Google account${e?` (${e})`:""}.`],
    [/^Connexion impossible : (.+)$/, (m,e)=>`Can't connect: ${e}`],
    [/^(.+) · (\d+) jours? restants?$/, (m,a,n)=>`${a} · ${n} ${s(n,"day")} left`],
    [/^Meilleur rang ce mois : (.+?)(?: · série de (\d+) victoires)?$/, (m,a,n)=>`Best rank this month: ${a}${n?` · ${n}-win streak`:""}`],
    [/^Depuis le début : (.+?) · Duels entre amis : (\d+) V · (\d+) D · (\d+) É · Collection : (\d+)\/(\d+) cartes\.$/, (m,a,w,l,d,o,t)=>`All-time: ${a==="aucune partie"?"no games":vde(" · "+a).slice(3)} · Duels with friends: ${w} W · ${l} L · ${d} D · Collection: ${o}/${t} cards.`],
    [/^· coût (-?\d+) · puissance (-?\d+)(.*)$/, (m,c,p,r)=>`· cost ${c} · power ${p}${r}`],
    [/^· (\d+-\d+) · (.+)$/, (m,a,b)=>`· ${a} · ${b==="IA"?"AI":b==="Ami"?"Friend":b}`],
    [/^Sept paliers : (.+)\. Chacun a trois divisions \(III, II, I\).*$/, (m,a)=>`Seven tiers: ${a}. Each has three divisions (III, II, I), except Herald and Avatar which have five (V to I). You need 3 stars per division in Wanderer and Initiate, 4 in Agent and Chosen, 5 in Herald and Avatar.`],
    [/^(.+) · il y a (\d+) (min|h|j)$/, (m,a,n,u)=>`${a} · ${n} ${u==="j"?"d":u} ago`],
    [/^(.+) · à l'instant$/, (m,a)=>`${a} · just now`],
    [/^(\d+) étoiles? sur (\d+)$/, (m,a,b)=>`${a} ${s(a,"star")} out of ${b}`],
    /* collection */
    [/^(\d+)\/12 · actif$/, (m,n)=>`${n}/12 · active`],
    [/^Touche une carte de ta collection pour l'ajouter ou la retirer\. Une seule copie par carte\. Coût moyen : (.+?)( ·)?\.?$/, (m,a,d)=>`Tap a card from your collection to add or remove it. One copy per card. Average cost: ${a}${d||"."}`],
    [/^Toutes les cartes · (\d+)\/(\d+)$/, (m,a,b)=>`All cards · ${a}/${b}`],
    [/^Encore (\d+) cartes? à ajouter$/, (m,n)=>`${n} more ${s(n,"card")} to add`],
    [/^(.+) · dès le (.+)$/, (m,a,d)=>`${a} · from ${d}`],
    [/^Disponible le (.+)$/, (m,d)=>`Available on ${d}`],
    [/^Possède (.+)$/, (m,a)=>`Requires ${a}`],
    [/^(.+) uniquement$/, (m,a)=>`${a} only`],
    [/^(.+) exige (.+) dans le deck\.$/, (m,a,b)=>`${a} requires ${b} in the deck.`],
    [/^(.+) a quitté le deck : elle exige (.+)\.$/, (m,a,b)=>`${a} left the deck: she requires ${b}.`],
    [/^Une seule ultra-légendaire par deck : retire d'abord (.+)\.$/, (m,a)=>`Only one ultra-legendary per deck: remove ${a} first.`],
    [/^Une seule version par personnage : retire d'abord (.+)\.$/, (m,a)=>`Only one version per character: remove ${a} first.`],
    [/^Choisis les 3 cartes affichées sur l'accueil · (\d)\/3\. La première choisie passe au centre\.$/, (m,n)=>`Choose the 3 cards shown on the home screen · ${n}/3. The first one chosen goes in the centre.`],
    [/^Chaque carte de ta collection débloque son portrait · (\d+)\/(\d+)$/, (m,a,b)=>`Each card in your collection unlocks its portrait · ${a}/${b}`],
    [/^Ta collection compte assez de cartes (.+)\. (.+) rejoint ta faction\.$/, (m,f,n)=>`Your collection holds enough ${({Jugement:"Judgement","Désir":"Desire"})[f]||f} cards. ${n} joins your faction.`],
    [/^Prométhée garde (\d+) énergie en réserve \((.+)\)$/, (m,k,w)=>`Prometheus keeps ${k} energy in reserve (${w==="L'adversaire"?'the opponent':w})`],
    [/^Tu possèdes (.+)\. Leur fusion ultra-légendaire t'attend\.$/, (m,a)=>`You own ${a}. Their ultra-legendary fusion awaits.`],
    [/^Agrandir (.+)$/, (m,a)=>`Enlarge ${a}`],
    [/^Mettre en avant (.+)$/, (m,a)=>`Feature ${a}`],
    [/^(.+) \(verrouillé\)$/, (m,a)=>`${a} (locked)`],
    [/^(.+), coût (\d+), puissance (-?\d+)$/, (m,a,c,p)=>`${a}, cost ${c}, power ${p}`],
    [/^(.+), puissance (-?\d+)$/, (m,a,p)=>`${a}, power ${p}`],
    [/^· coût (\d+) · puissance (-?\d+)$/, (m,c,p)=>`· cost ${c} · power ${p}`],
    [/^· coût (\d+) · puissance (-?\d+)(.*)$/, (m,c,p,r)=>`· cost ${c} · power ${p}${r}`],
    /* boutique */
    [/^Édition limitée · (\d+) cartes$/, (m,n)=>`Limited edition · ${n} cards`],
    [/^(\d+) cartes$/, (m,n)=>`${n} cards`],
    [/^(.+) · doublon \+(\d+)$/, (m,a,v)=>`${a} · duplicate +${v}`],
    [/^(\d+) cartes? de ces raretés à trouver · au moins une nouvelle par pack$/, (m,n)=>`${n} ${s(n,"card")} of these rarities to find · at least one new per pack`],
    [/^Il manque (\d+) CHF$/, (m,n)=>`${n} CHF short`],
    [/^Dès le (.+)$/, (m,d)=>`From ${d}`],
    [/^Disponible jusqu'au (.+)$/, (m,d)=>`Available until ${d}`],
    [/^Du (.+) au (.+)$/, (m,a,b)=>`From ${a} to ${b}`],
    [/^Victoire \+(\d+) · égalité \+(\d+) · défaite \+(\d+) CHF$/, (m,w,d,l)=>`Win +${w} · draw +${d} · loss +${l} CHF`],
    [/^Victoire \+(\d+) · égalité \+(\d+) · défaite \+(\d+) CHF · collection (\d+)\/(\d+)$/, (m,w,d,l,a,b)=>`Win +${w} · draw +${d} · loss +${l} CHF · collection ${a}/${b}`],
    [/^Trois cartes au choix chaque jour, à prix fixe : (\d+) CHF la Rare, (\d+) CHF l'Épique\. Les cartes que tu n'as pas passent en priorité\.$/, (m,r,e)=>`Three cards to choose from each day, at a fixed price: ${r} CHF for a Rare, ${e} CHF for an Epic. Cards you don't own come first.`],
    [/^(\d+) CHF · il en manque (\d+)$/, (m,p,n)=>`${p} CHF · ${n} short`],
    [/^Acheter · (\d+) CHF$/, (m,p)=>`Buy · ${p} CHF`],
    [/^Doublon · \+(\d+) CHF$/, (m,v)=>`Duplicate · +${v} CHF`],
    /* classement */
    [/^Classement · (.+)$/, (m,a)=>`Rankings · ${a}`],
    [/^(.+) \(toi\)$/, (m,a)=>`${a} (you)`],
    [/^(.+) · (\d+) V · (\d+) D$/, (m,a,w,l)=>`${a} · ${w} W · ${l} L`],
    [/^(\d+) joueurs? cette saison$/, (m,n)=>`${n} ${s(n,"player")} this season`],
    /* duel */
    [/^Un duel contre (.+) peut être repris\.$/, (m,a)=>`A duel against ${a} can be resumed.`],
    [/^\. En attente de (.+)…$/, (m,a)=>`. Waiting for ${a}…`],
    [/^En attente de (.+)…$/, (m,a)=>`Waiting for ${a}…`],
    [/^(.+) arrive, la partie commence…$/, (m,a)=>`${a} is arriving, the game is starting…`],
    [/^Connecté à (.+)\. La partie commence…$/, (m,a)=>`Connected to ${a}. The game is starting…`],
    [/^(.+) a quitté le salon$/, (m,a)=>`${a} left the room`],
    [/^Duel contre (.+)$/, (m,a)=>`Duel against ${a}`],
    /* blitz */
    [/^(\d) victoires? · IA (.+)$/, (m,n,t)=>`${n} ${s(n,"win")} · ${t} AI`],
    [/^Lancer un Blitz · (\d+) CHF$/, (m,p)=>`Start a Blitz · ${p} CHF`],
    [/^Ta partie gratuite revient dans (\d+) h\.$/, (m,h)=>`Your free game returns in ${h} h.`],
    [/^(\d) victoires? sur 3( : Blitz parfait\.|\.)$/, (m,n,e)=>`${n} ${s(n,"win")} out of 3${e==="."?".":": perfect Blitz."}`],
    [/^Choix (\d) \/ 8$/, (m,n)=>`Pick ${n} / 8`],
    [/^Match (\d) \/ 3$/, (m,n)=>`Match ${n} / 3`],
    [/^\. Tu tiens déjà (\d+) CHF\.$/, (m,n)=>`. You already hold ${n} CHF.`],
    [/^\. Gagne pour décrocher ta première récompense\.$/, ()=>`. Win to earn your first reward.`],
    [/^Abandonner le Blitz(?: et prendre (\d+) CHF)?$/, (m,n)=>`Quit the Blitz${n?` and take ${n} CHF`:""}`],
    [/^Blitz · (\d) victoires? sur 3$/, (m,n)=>`Blitz · ${n} ${s(n,"win")} out of 3`],
    [/^Blitz terminé : \+(\d+) CHF$/, (m,n)=>`Blitz over: +${n} CHF`],
    [/^Prochain match contre une IA (.+)$/, (m,t)=>`Next match against a ${t} AI`],
    /* partie */
    [/^Révélé au tour (\d)$/, (m,n)=>`Revealed on turn ${n}`],
    [/^Il sera révélé au début du tour (\d)\.$/, (m,n)=>`It will be revealed at the start of turn ${n}.`],
    [/^À toi, (.+)$/, (m,a)=>`Your turn, ${a}`],
    [/^toi (-?\d+)$/, (m,n)=>`you ${n}`],
    [/^adversaire (-?\d+)$/, (m,n)=>`opponent ${n}`],
    [/^prochaine carte −(\d+)$/, (m,n)=>`next card −${n}`],
    [/^\+(\d+) au prochain tour$/, (m,n)=>`+${n} next turn`],
    [/^Coût (-?\d+) · Puissance (-?\d+)(.*)$/, (m,c,p,r)=>`Cost ${c} · Power ${p}${r===" · Pas d'effet."?" · No effect.":r}`],
    [/^Coût (-?\d+) · puissance de base (-?\d+)( · actuelle)?$/, (m,c,p,a)=>`Cost ${c} · base Power ${p}${a?" · current":""}`],
    [/^(.+) Vritra a verrouillé ce lieu : plus personne ne peut y jouer\.$/, (m,a)=>`${a} Vritra locked this location: no one can play here anymore.`],
    [/^(.+) · effets continus et lieu$/, (m,a)=>`${a} · ongoing effects and location`],
    [/^(.+) · Poison de Médée$/, (m,a)=>`${a} · Medea's poison`],
    [/^(.+) · (Le Tatoueur|Le glas|Mjölnir|Loviatar)$/, (m,a,b)=>`${a} · ${exact[b]}`],
    [/^(.+) · Floraison passée$/, (m,a)=>`${a} · Blossom passed`],
    [/^(.+) · Vasseur \(paiement\)$/, (m,a)=>`${a} · Vasseur (payment)`],
    [/^⚖ Serment sur (.+) \?$/, (m,a)=>`⚖ Oath on ${a}?`],
    [/^Tu remportes (\d) lieux sur 3\. (.+)$/, (m,n,r)=>`You win ${n} locations out of 3. ${exact[r]||r}`],
    [/^(\d) lieux? contre (\d)(?: · départage à la puissance totale (-?\d+) contre (-?\d+))?$/, (m,a,b,x,y)=>`${a} ${s(a,"location")} to ${b}${x?` · decided on total Power ${x} to ${y}`:""}`],
    [/^Quête accomplie : (.+)\. Récupère ta récompense à l'accueil\.$/, (m,a)=>`Quest complete: ${a}. Claim your reward on the home screen.`],
    /* journal */
    [/^Tour (\d) · lieu révélé : (.+)$/, (m,n,l)=>`Turn ${n} · location revealed: ${l}`],
    [/^Tour (\d)$/, (m,n)=>`Turn ${n}`],
    [/^Partie guidée · tour (\d)\/6$/, (m,n)=>`Guided game · turn ${n}/6`],
    [/^Adversaire : deck (.+) · niveau (.+)$/, (m,f,t)=>`Opponent: ${f} deck · level ${t}`],
    [/^Blitz · match (\d)\/3 · adversaire (.+), niveau (.+)$/, (m,n,f,t)=>`Blitz · match ${n}/3 · ${f} opponent, level ${t}`],
    [/^(Idunn|Ishtar) · ([+−]\d+) à (.+) \((.+)\)$/, (m,c,v,a,w)=>`${c} · ${v} to ${a} (${who(w)})`],
    [/^Dante · \+1 \((.+)\)$/, (m,w)=>`Dante · +1 (${who(w)})`],
    [/^La Messagère d'Hécate · \+(\d+) \((.+)\)$/, (m,v,w)=>`Hecate's Messenger · +${v} (${who(w)})`],
    [/^Médée · −2 à (.+) \((.+)\)$/, (m,a,w)=>`Medea · −2 to ${a} (${who(w)})`],
    [/^Le Cirque mélange les puissances de (\d+) cartes$/, (m,n)=>`The Circus shuffles the power of ${n} cards`],
    [/^La Faille détruit (.+) \((.+)\)$/, (m,a,w)=>`The Rift destroys ${a} (${who(w)})`],
    [/^Lac Ouchy · un Reflet apparaît \((.+)\)$/, (m,w)=>`Lake Ouchy · a Reflection appears (${who(w)})`],
    [/^L'adversaire jure sur (.+)$/, (m,a)=>`The opponent swears on ${a}`],
    [/^Serment croisé sur (.+)$/, (m,a)=>`Cross Oath on ${a}`],
    [/^Konohanasakuya-Hime · la floraison est passée \((.+)\)$/, (m,w)=>`Konohanasakuya-hime · the blossom has passed (${who(w)})`],
    [/^Poison de Médée · −1 à (.+) \((.+)\)$/, (m,a,w)=>`Medea's poison · −1 to ${a} (${who(w)})`],
    [/^Thor récupère Mjölnir : \+2 \((.+)\)$/, (m,w)=>`Thor gets Mjölnir back: +2 (${who(w)})`],
    [/^Le glas sonne : \+(\d+) à (\d+) cartes? \((.+)\)$/, (m,v,n,w)=>`The knell tolls: +${v} to ${n} ${s(n,"card")} (${who(w)})`],
    [/^Le Tombeau rend (\d+) cartes? \((.+)\)$/, (m,n,w)=>`The Tomb gives back ${n} ${s(n,"card")} (${who(w)})`],
    [/^Toi · (\d+)$/, (m,n)=>`You · ${n}`], [/^Adversaire · (\d+)$/, (m,n)=>`Opponent · ${n}`],
    [/^Main adverse : (\d+)$/, (m,n)=>`Enemy hand: ${n}`],
    [/^Serment prêté sur (.+)$/, (m,a)=>`Oath sworn on ${a}`],
    [/^Vasseur paie : \+4 \((.+)\)$/, (m,w)=>`Vasseur pays: +4 (${who(w)})`],
    [/^[^→]+ · [^→]+$/, m=>{ const p=m.split(" · "); return p.every(x=>exact[x]!==undefined)?p.map(x=>exact[x]).join(" · "):m; }],
    [/^(.+?) · (.+?) → (.+?)(?: \((.+)\))?$/, (m,w,c,l,n)=>`${who(w)} · ${c} → ${l}${n?` (${note(n)})`:""}`]
  ];
  function vde(r){ return r?r.replace(/(\d+) V · (\d+) D · (\d+) É/,"$1 W · $2 L · $3 D"):""; }

  window.HELVARA_UI_EN={
    exact, rules, note,
    data:{
      TIERS:["Wanderer","Initiate","Agent","Chosen","Herald","Avatar","Deity of Helvara"],
      MONTHS:["January","February","March","April","May","June","July","August","September","October","November","December"],
      QDEF:{cheap5:"Play 5 cards that cost 1 or 2",helv4:"Play 4 Helvara cards",move2:"Move 2 cards",disc3:"Discard 3 cards",six6:"Play a 6-cost card on turn 6",oath:"Keep an Oath",fusion:"Play an Ultra-Legendary",blitz1:"Win a Blitz game",facwin:"Win a game with at least 6 {f} cards in your deck",charwin:"Win a game with {c} in play",play3:"Play 3 games",cards12:"Play 12 cards",loc15:"Win a location with 15 Power or more",win3:"Win 3 games",sweep:"Win all 3 locations in one game",kill4:"Destroy or erase 4 enemy cards",power40:"Finish a game with 40 total Power or more"},
      PACKS:{
        brulure:{name:"First Burn",desc:"Your first deck: 12 different cards, including 2 epics, with a playable cost curve. One time only."},
        reflets:{name:"Bundle of Reflections",desc:"Commons and rares. To fill in the basics."},
        voile:{name:"Seal of the Veil",desc:"Epics come into play."},
        breche:{name:"Breach of the Seal",desc:"Anything can come out of it, legendaries included."},
        halloween:{name:"Pumpkin Fold",desc:"Halloween edition. More epics and legendaries than anywhere else."},
        nouvelan:{name:"Twelfth Stroke Fold",desc:"New Year edition. More epics and legendaries than anywhere else."},
        noel:{name:"Star Fold",desc:"Christmas edition. More epics and legendaries than anywhere else."}
      },
      SEASON:{
        halloween:{sub:"Pumpkin Night",who:"Player of Helvara · Halloween night",eyebrow:"Pumpkin Night · until November 2",title:"The veil is thin in Helvara",hint:"Pumpkins burn along the quays. The Pumpkin Fold hides Lady Joanna, and Morrigan, Nyx, Izzy, Yarden, Ares, Nergal and Medea in their Halloween versions.",btn:"Open the Pumpkin Fold",win:"Victory under the russet moon",lose:"The dead won tonight"},
        noel:{sub:"Star Vigil",who:"Player of Helvara · Christmas Eve",eyebrow:"Star Vigil · until January 2",title:"Snow falls on Helvara",hint:"The vineyards are white and the lake holds its breath. The Star Fold hides Aphrodite, Sekhmet, Calypso and Apsu in their Christmas versions.",btn:"Open the Star Fold",win:"Victory under the Star",lose:"The winter night prevails"},
        nouvelan:{sub:"Twelfth Stroke Night",who:"Player of Helvara · New Year's Eve",eyebrow:"Twelfth Stroke Night · until January 18",title:"Midnight strikes over Helvara",hint:"The cathedral counts the strokes and the dead are listening. The Twelfth Stroke Fold hides Hel, Eos, Pele and Qetesh in their New Year's Eve versions.",btn:"Open the Twelfth Stroke Fold",win:"Victory on the last stroke",lose:"The year left without you"}
      },
      DROPS:{
        nov15:"Prometheus keeps the fire, Pandora opens the box, Athena guides your hand, and Styx watches over her daughters: Bia, and Nike, the first faction ultra-legendary. 8 Judgement cards are enough to get her.",
        dec26:"Odin, Thor, Hel, Baldur, Hades, Poseidon, Circe, Qetesh, the people of Lausanne… five new fusions and the Creator's Domain.",
        oct26:"Lilith, Ereshkigal, Psyche, Amaterasu, the Mother of Ash… and the first ultra-legendary, Yarden X Apsu.",
        nov26:"Nemesis, Anubis, Susanoo, Aphrodite, Medea, the Flon Thief… and three new fusions: Aphrodite X Yarden, Calypso X Jordan, Nemesis X Jordan."
      },
      ULS:{nike:"8 Judgement cards, Nike included",ulya:"Yarden Weiss and Apsu",ulji:"Jordan and Izzy",ulaph:"Aphrodite and Yarden Weiss",ulcal:"Calypso and Jordan",ulnem:"Nemesis and Jordan",ulcirce:"Nyx and Circe",uloshun:"Nyx and Oshun",ulqetjor:"Qetesh and Jordan",ulqetyar:"Qetesh and Yarden Weiss",ulhel:"Hel and Baldur",ulpele_r:"Pele and Jordan",ulqetjor_r:"Qetesh of the New Year and Jordan",ulsomnambule:"The Sleepwalker and The Queen",ularchiviste:"The Archivist and The Proprietress"}
    }
  };
})();
